name: 'Add Values'
description: 'Adds two values'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
outputs:
  sum-of-numbers:
    description: "Sum of inputs"
    value: ${{ toJSON(steps.number-addition.outputs) }}
runs:
  using: "composite"
  steps:
    - name: Adds Two Numbers
      id: number-addition
      run: |
         echo ${{ fromJSON(inputs.actionInputs) }}
         echo Uno ${{ fromJSON(inputs.actionInputs).first }}
         echo "First Number ${FIRST_NUMBER}"
         echo "Second Number: ${SECOND_NUMBER}"
         addResult=$((FIRST_NUMBER + SECOND_NUMBER))
         echo "result=${addResult}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).SECRET1 }}
        FIRST_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-first-value }}
        SECOND_NUMBER: ${{ fromJSON(inputs.actionInputs).add-action-second-value }}



